version: 0.2

phases:
  install:
    runtime-versions:
      java: correto8
  pre_build:
    commands:
      - echo Nothing to do
  build:
    commands:
      - echo Building jar
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/grocery-1.0.jar